name: 📅 Build Static Site to static-site Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout main
        uses: actions/checkout@v4

      - name: 👌 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ⚡ Install dependencies
        run: pnpm install

      - name: 📆 Build and Export site
        run: |
          pnpm build
          pnpm export

      - name: 🚀 Push static to static-site branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: static-site
          publish_dir: ./out
          force_orphan: true
