name: 🚧 Deploy via FTP to Hostinger

on:
  push:
    branches:
      - static-site

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout static-site
        uses: actions/checkout@v4

      - name: 🚜 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_TARGET_DIR }}/
          dangerous-clean-slate: true
